class Openrag < Formula
  include Language::Python::Virtualenv

  desc "Comprehensive Retrieval-Augmented Generation platform built on Langflow, Docling, and Opensearch"
  homepage "https://github.com/bendevergerona/openrag"
  url "https://github.com/bendevergerona/openrag.git"
  version "0.1.25"
  license "Apache-2.0"
  head "https://github.com/bendevergerona/openrag.git", branch: "main"

  # Python version requirement from pyproject.toml
  depends_on "python@3.13"
  
  # Build dependencies
  depends_on "rust" => :build
  depends_on "cmake" => :build
  depends_on "pkg-config" => :build
  
  # Runtime dependencies
  depends_on "cairo"
  depends_on "glib"
  depends_on "pango"

  def install
    # Set up virtualenv
    venv = virtualenv_create(libexec, "python3.13")
    
    # Install package using pip with all extras
    system libexec/"bin"/"pip", "install", "--verbose",
           "--no-binary", ":all:",
           "--ignore-installed",
           ".",
           "--prefix=#{libexec}"
    
    # Create wrapper scripts
    bin.install_symlink libexec/"bin"/"openrag"
    
    # Create necessary directories
    (prefix/"etc"/"openrag").mkpath
    (prefix/"var"/"log"/"openrag").mkpath
    (prefix/"var"/"lib"/"openrag").mkpath
  end

  def post_install
    # Create default configuration if it doesn't exist
    config_file = etc/"openrag"/"config.env"
    unless config_file.exist?
      config_file.write <<~EOS
        # OpenRAG Configuration
        # Generated by Homebrew on #{Time.now}
        
        # Add your environment variables here
        # OPENRAG_DATA_DIR=#{var}/lib/openrag
        # OPENRAG_LOG_DIR=#{var}/log/openrag
      EOS
    end
  end

  def caveats
    <<~EOS
      OpenRAG has been installed successfully!

      To get started:
        1. Run: openrag
        2. Configure environment variables in: #{etc}/openrag/config.env
        3. Documentation: https://github.com/bendevergerona/openrag

      Directories:
        • Configuration: #{etc}/openrag/
        • Data:          #{var}/lib/openrag/
        • Logs:          #{var}/log/openrag/

      Requirements:
        • Python 3.13+
        • Sufficient disk space for model weights (~2-5GB)
        • Internet connection for downloading models

      Note: First run may take time to download required models.
    EOS
  end

  test do
    # Test that the command is available
    assert_match "openrag", shell_output("#{bin}/openrag --help")
    
    # Test Python module import
    system "python3.13", "-c", "import sys; sys.path.insert(0, '#{libexec}/lib/python3.13/site-packages'); import openrag"
  end
end
